### ISSUE TITLE
战双帕米什

### ISSUE THREAD

**Issue by ambesia33** [gachagamescape/gachagamescape.github.io#1]
# 战双帕弥什
https://pns.kurogame.com/

## 2023 夏活只给男角色出泳装    分体分魂的玩家克隆人与女角色生离死别，玩家本体一无所知   角色机体提前迭代，男装甲踢掉上岗时间极短的女装甲，且作为辅助位的装甲型伤害比所有女进攻型高  328池子皮肤剧情抛开玩家写2女1男间的互动
2022 男角色超刻结算过于媚女，玩家炎上无果
2021 女角色蒲牢被微博冲和谐 大量皮肤和角色本体和谐
2020 cp向剧情残留 后续有官方短漫招魂

## 站双虽然号称ml游戏 但是角色好感剧情与主线时间线对不上，被自家玩家定位if线or平行世界，即实际上玩家与角色间的羁绊并不深，甚至突兀。

分身雷

**Comment by xiatg** [comment]
非常感谢您拨冗写下的投稿！为了保证投稿符合文档收录标准，在此为您提出以下修改建议：
1. 请首先使用投稿须知中存在的标签，再添加自己认为需要的标签。
2. 如果您希望对剧情进行分类，请明确写出剧情的出处。例如，主线剧情XX章，或者是XX角色的XX剧情。
3. 对于运营事件，时间请务必精确到月日。

您可以参考[尘白禁区](https://gachagamescape.github.io/%E5%B0%98%E7%99%BD%E7%A6%81%E5%8C%BA.html)页面的格式进行编辑，此页面的Markdown源码在[这里](https://raw.githubusercontent.com/gachagamescape/gachagamescape.github.io/main/docs/%E5%B0%98%E7%99%BD%E7%A6%81%E5%8C%BA.md)。

祝您生活愉快！
