### ISSUE TITLE
战双帕弥什

### ISSUE THREAD

**Issue by ambesia33** [gachagamescape/gachagamescape.github.io#2]
# 战双帕弥什
[游戏官网链接](https://pns.kurogame.com/)

## 标签 
 <Badge text="国服" type="info"/> <Badge text="台服服" type="info"/> <Badge text="日服服" type="info"/> <Badge text="韩服" type="info"/> <Badge text="国际服" type="info"/> <Badge text="玩家性别不明" type="tip"/>  <Badge text="含有男性自机角色" type="tip"/> <Badge text="含有女性与玩家的好感剧情" type="tip"/><Badge text="含有性男与玩家的好感剧情" type="tip"/><Badge text="含有CP剧情" type="tip"/><Badge text="分身雷" type="tip"/>

### 主线故事
|标题|标签|解释|
|:-:|:-:|:-:|
|摇篮游行|<Badge text="分身雷" type="tip"/>|玩家的分体分魂的克隆人与女角色拉弥亚|

### 活动剧情
|标题|标签|解释|
|:-:|:-:|:-:|
|意识营救战|<Badge text="含有cp剧情" type="tip"/>|渡边与比安卡

### 活动剧情
|标题|标签|解释|
|:-:|:-:|:-:|
|绮影凛然|<Badge text="含有cp剧情" type="tip"/>|薇拉 21号和诺克提||

## 运营历史

2023年11月16日，推出328元的卡池皮肤，配套剧情<Badge text="含有cp剧情" type="tip"/>
-->
2023年9月28日，推出男角色渡边尘铭，打破角色下岗周期规律，并给予了破格的数值，装甲型伤害远高于其他进攻型。

2023年7月20日,推出摇篮游行版本，做为夏活版本，泳装皮肤仅有两个男角色。

2023年7月20日，推出摇篮游行版本，主线玩家的克隆人与角色经历生离死别<Badge text="分身雷" type="tip"/>而玩家本体一无所知。

2020年12月25日，日服推出特供丁字裤皮肤，而国服早前大量皮肤和谐

2019年12月5日，战双帕弥什开服，标榜ml游戏实际好感剧情与主线无法对应，被玩家归类为if线or平行世界

## 标签解释
|标签|解释|
|:-:|:-:|
|国服|此游戏在国服运营。|
|台服|此游戏在台湾服运营。|
|韩服|此游戏在韩国服运营。|
|日服服|此游戏在日本服运营。|
|国际服|此游戏在全球服运营。|
|玩家性别不明|此游戏中玩家性别不明。|
|含有男性自机角色|此游戏中可获得角色含有男性自机角色。|
|含有女性与玩家的好感剧情|此游戏中存在女性与玩家的好感剧情。|
|含有男性与玩家的好感剧情|此游戏中存在男性与玩家的好感剧情。|
|含有cp剧情|此游戏中存在女性与男性的好感剧情。|
|分身雷|此游戏中存在女性与玩家的克隆人好感剧情。|

**Comment by xiatg** [comment]
您好，非常感谢您高质量的投稿！在收录之前，我希望做一些细小的修改：

1. 根据您的描述，似乎此游戏国服与日服有游戏内容上的差距，那么我认为应该将此页面描述的内容限定于国服。
2. 修改一些标签的错误格式。

基于以上修改意见，此页面修改后的内容如下：
请您确认以下修改后的内容。在得到您的认可后，我将收录这段内容。

# 战双帕弥什
[游戏官网链接](https://pns.kurogame.com/)

## 标签 
 <Badge text="国服" type="info"/> <Badge text="玩家性别不明" type="tip"/>  <Badge text="含有男性自机角色" type="caution"/> <Badge text="含有女性与玩家的好感剧情" type="tip"/> <Badge text="含有男性与玩家的好感剧情" type="danger"/> <Badge text="含有CP剧情" type="danger"/> <Badge text="分身雷" type="caution"/> <Badge text="含有和谐" type="caution"/>

## 剧情分类

### 主线故事
|标题|标签|解释|
|:-:|:-:|:-:|
|摇篮游行|<Badge text="分身雷" type="caution"/>|玩家的分体分魂的克隆人与女角色拉弥亚|

### 活动剧情
|标题|标签|解释|
|:-:|:-:|:-:|
|意识营救战|<Badge text="含有cp剧情" type="danger"/>|渡边与比安卡

### 活动剧情
|标题|标签|解释|
|:-:|:-:|:-:|
|绮影凛然|<Badge text="含有cp剧情" type="danger"/>|薇拉 21号和诺克提||

## 运营历史

2023年11月16日，推出328元的卡池皮肤，配套剧情<Badge text="含有cp剧情" type="danger"/>。

2023年9月28日，推出男角色渡边尘铭，打破角色下岗周期规律，并给予了破格的数值，装甲型伤害远高于其他进攻型。

2023年7月20日，推出摇篮游行版本，作为夏活版本，泳装皮肤仅有两个男角色。

2023年7月20日，推出摇篮游行版本，主线玩家的克隆人与角色经历生离死别<Badge text="分身雷" type="caution"/>而玩家本体一无所知。

2020年12月25日，日服推出特供丁字裤皮肤，而国服早前大量皮肤和谐

2019年12月5日，战双帕弥什开服，标榜ml游戏实际好感剧情与主线无法对应，被玩家归类为if线or平行世界

## 标签解释
|标签|解释|
|:-:|:-:|
|国服|此游戏在国服运营。|
|玩家性别不明|此游戏中玩家性别不明。|
|含有男性自机角色|此游戏中可获得角色含有男性自机角色。|
|含有女性与玩家的好感剧情|此游戏中存在女性与玩家的好感剧情。|
|含有男性与玩家的好感剧情|此游戏中存在男性与玩家的好感剧情。|
|含有cp剧情|此游戏中存在女性角色与男性角色的好感剧情。|
|分身雷|此游戏中存在女性与玩家的克隆人好感剧情。|
|含有和谐|此游戏中存在美术资源的和谐。|

**Comment by ambesia33** [comment]
![image](https://github.com/gachagamescape/gachagamescape.github.io/assets/156564893/b17397ff-2c7a-4e51-8616-be91e76d9cb1)
我这边看到的标签是没有显示，如果你那边看是正常的话收录即可

**Comment by xiatg** [comment]
您的投稿已收录。再次感谢您的高质量投稿！
