### ISSUE TITLE
讨论：添加关于游戏的更多信息

### ISSUE THREAD

**Issue by inkydragon** [gachagamescape/gachagamescape.github.io#4]
我想到的一些点，并不一定都值得加，可以讨论。
+ 一句话简介
	建议直接抄B站或者渠道商的介绍，也可以参考B站账号的自我介绍。
+ 标签
	+ 如果是有男性角色，可以考虑直接放出对应的链接，有 wiki 最好，没有就放官方的角色预告公告
	+ PVP/PVE，是否有排行榜 这类标签也可以考虑
+ 官方在各个平台的账号
	一是看内容，二是看社区风气。
	- 其他地区的官网。考虑到某些游戏会更推荐外服
	- B站主页，这个还是比较有用的，宣传视频默认放在这里
	- Youtube 主页，外服游戏的宣传视频
	- B站游戏页面（如果有）。忽略评分，主要是看大家锐评
	- AppStore（如果有）。看看锐评
	- X (推特)，外服游戏的主账号
	- ....
	- 其他的讨论社区：TapTap、贴吧、NGA、Reddit...。
	    这个可能引用特定的游戏入坑贴会比较有用。安利的时候大家都会说各种优势，可以兼听则明。
	- 备选的还有微博超话/#TAG#和小红书官号。
	    但是这个两个平台并不是所有人都会关注。不过有没有小红书官号，是否发起过活动，是一个观察的角度。
+ 主线故事:
	可以考虑添加指向剧情合集的链接。有些游戏有全文本的剧情站，大多数则是B站能找到剧情合集。
	可以用于引用特定的剧情，以佐证某些分类标签。
+ 运营历史
	同上，可以添加官网、B站对应的动态或视频链接
+ 氪金模式
	刚开始可以简单的写一些 XX-like，后面或许能给这些游戏分分类
	+ 氪金/游戏货币兑换比例
	+ 大小月卡获得游戏货币
	+ 普池、限定、武器、... 对应的抽取货币、出货比例、是否有保底

**Comment by xiatg** [comment]
非常感谢您拨冗提供想法！以下是我的一些想法：

> 一句话简介
> PVP/PVE，是否有排行榜 这类标签也可以考虑
> 氪金模式
> 官方在各个平台的账号

本文档目前是希望能够收集更多与男性向内容有关的游戏属性/剧情/运营事件，比较通用的一些属性/信息暂时不在收录范围。

> 官方在各个平台的账号

您提到的根据各个平台账号的内容/风气来判断对男性向内容的影响，其实可以作为标签解释/剧情解释/运营事件来收录进来。本文档的目标之一就是能够抽丝剥茧，排除人为的因素，通过列举真实的例子来反映一个游戏男性向内容的好坏。

> 如果是有男性角色，可以考虑直接放出对应的链接，有 wiki 最好，没有就放官方的角色预告公告
> 主线故事
> 运营历史

我认为您描述的这些都是对于标签/运营事件更加详细的佐证，如果有是非常好的。由于目前文档收录的数量很少，为了能先提高稿件数量，对稿件在提供证据的这方面要求还没有很高，因此在issue template里并没有强求提供上述内容。但是我认为可以将这些内容作为推荐添加的证据加入到template中。

**Comment by inkydragon** [comment]
大概理解了，核心关注点是是否影响男性向的内容。
那就先以提高收录数量为目标吧，之后再追求质量和其他内容。
