### ISSUE TITLE
グランブルーファンタジー(碧蓝幻想)

### ISSUE THREAD

**Issue by NikyMa** [gachagamescape/gachagamescape.github.io#5]
# グランブルーファンタジー(碧蓝幻想)
[官方网站](https://granbluefantasy.jp) 

## 标签 

<Badge text="日服" type="info"/><Badge text="玩家性别可选" type="tip"/> <Badge text="含有男性自机角色" type="warning"/><Badge text="玩家不参与剧情" type="info"/> <Badge text="含有女性与玩家的好感剧情" type="info"/> <Badge text="含有男性与玩家的好感剧情" type="warning"/> <Badge text="含有百合剧情" type="danger"/> <Badge text="含有CP剧情" type="danger"/>
<Badge text="含有BL剧情" type="danger"/>

### 主线故事

|  标题   | 标签  | 解释 |
| :----: | :----: | :----: |
| 苍之少女篇  |  |  |
| 晓之空篇  |  |  |
| 星之旅人篇  |  |  |

### 活动剧情

|  标题   | 标签  | 解释 |
| :----: | :----: | :----: |
| 届かないほど、近くのあなたへ  |  |  |
| 000  | <Badge text="含有男性与玩家的好感剧情" type="warning"/><Badge text="含有BL剧情" type="danger"/>| 芬和特异点的羁绊；天司组bl营业 |
| OLD BOND  |  |  |
| and you  |  |  |
| Unbound Asterism  |  <Badge text="含有百合剧情" type="danger"/> <Badge text="玩家不参与剧情" type="tip"/>  | 虹弓和土金月拳百合cp；主角全程摄像头|

### 个人故事

|  标题   | 标签  | 解释 |
| :----: | :----: | :----: |
|   |  |  |
|   |  |  |
|   |  |  |

## 运营历史

2023年12月24日，宣布联动《我的英雄学院》，并于2024年1月12日正式上线。

## 标签解释

| 标签  | 解释 |
| :----: | :----: |
|  日服  | 此游戏在日本运营 |  
| 玩家性别可选  | 此游戏中玩家性别可选 |  
|  玩家不参与剧情   | 此游戏中存在主角不参与的剧情 | 
|  含有男性自机角色  | 此游戏中可获得角色含有男性 | 
|  含有女性与玩家的好感剧情   | 此游戏中存在女性与玩家的好感剧情 | 
|  含有男性与玩家的好感剧情   | 此游戏中存在男性与玩家的好感剧情 | 
|  含有百合剧情  | 此游戏中存在百合剧情 | 
|  含有CP剧情   | 此游戏中存在CP剧情 | 
|  含有BL剧情   | 此游戏中存在BL剧情 |

**Comment by xiatg** [comment]
您好！非常感谢您拨冗投稿！在此提供一些修改意见：

我注意到您在运营历史中提到了《我的英雄学院》联动，但是您的描述似乎并没有反映出这个事件对游戏的男性向内容有什么影响。本文档希望仅列举对男性向内容造成影响的事件。

其他部分的内容我认为是符合收录要求的。您可以考虑进一步解释/修改这部分内容，或者我会在经过您的许可后，删除这个事件，并把其他内容收录到文档中。

感谢您的时间，祝您生活愉快！

**Comment by inkydragon** [comment]
> 《我的英雄学院》联动

这个就得上知乎问题了。看标题就行

- 如何看待《我的英雄学院》作者堀越耕平将731人体实验受害者侮辱性称呼命名为漫画反派？
	https://www.zhihu.com/question/369386576
- 如何看待《我的英雄学院》作者堀越耕平与集英社的突发「道歉」?
	https://www.zhihu.com/question/370197731
- 新仇旧恨！盘点《我的英雄学院》和堀越耕平的七宗罪 
	https://www.bilibili.com/video/BV1w7411H7f6/
	这个视频 1300万 播放！惊了

**Comment by NikyMa** [comment]
> 您好！非常感谢您拨冗投稿！在此提供一些修改意见：
> 
> 我注意到您在运营历史中提到了《我的英雄学院》联动，但是您的描述似乎并没有反映出这个事件对游戏的男性向内容有什么影响。本文档希望仅列举对男性向内容造成影响的事件。
> 
> 其他部分的内容我认为是符合收录要求的。您可以考虑进一步解释/修改这部分内容，或者我会在经过您的许可后，删除这个事件，并把其他内容收录到文档中。
> 
> 感谢您的时间，祝您生活愉快！

您好，我考虑到本文档主要面向**中文社区的**后宫爱好者，所以把牵扯到政治的运营问题提了一下。

我在文档里写入了两段注释，一段解释了为什么写入**《我的英雄学院》联动**；另一段也建议了此文档不会牵扯到**非性取向的因素**，更多会从男性后宫爱好者角度出发。

如果您觉得《我的英雄学院》联动不符合该文档的主旨，可以删除这个事件，并把其他内容收录到文档中。

个人时间允许的话，后续会继续丰富该文档的内容。

**Comment by xiatg** [comment]
感谢您的理解！您的投稿已被收录。

再次感谢您花时间投稿！祝您生活愉快！
